language: go

go:
  - tip
  - 1.5.3
  - 1.4.3
  - 1.3.3
  - 1.2.2

env:
  - GIMME_OS=linux GIMME_ARCH=amd64
#  - GIMME_OS=darwin GIMME_ARCH=amd64
#  - GIMME_OS=windows GIMME_ARCH=amd64

matrix:
  allow_failures:
    - go: tip

install:
  - go get -d -v ./...

script:
  - go build -v
